
[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#FFD700"
backgroundColor = "#0f0f0f"
secondaryBackgroundColor = "#1a1a1a"
textColor = "white"
font = "sans serif"

[global]
pageTitle = "FURIA Fan Connect"
pageIcon = "🎮"
